name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    # if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      # - name: Echo secrets
      #   run: |
      #     echo APPLE_ID: ${{ secrets.APPLE_ID }}
      #     echo APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
      #     echo CSC_LINK: ${{ secrets.CSC_LINK }}
      #     echo CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      #     echo GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: |
          npm install

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_LINK: MIIJCQIBAzCCCM8GCSqGSIb3DQEHAaCCCMAEggi8MIIIuDCCA28GCSqGSIb3DQEHBqCCA2AwggNcAgEAMIIDVQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIBXrEDlJTKFcCAggAgIIDKNkNmn6DNtyU4XbRJIagkIhFzsd3l061mRUqkern/eaO9loHtWtNv9QQeTNMjSFFGtOB061drX4w8PAqIxcvW5A2ZTEf11J2Dr+q3dbNxcwK6DJ4T5NSS+PdZDrV6+Y1t3++NiRZTJPxRLfrrCYTNvG+/Dywr9oSGuVtr7RWO0ekB1Au4zLnLeKEIS3MciRAD30iiBatTkacBpxaO3nK2meyuGzv8ipwM5gUsveR5Hj04nYdxXYpD1ZncR2ACbtc73OReB9d+MpWmquxLcchG8jib/E4agw7Z50il7agypISsAS9KkG3U1AeMphDpQNAjwnVGDngpYA16bnr4O1YktdM7H0tt564W6wTvlRuun/othpyyhjmxVg7/Dub0H5z1XHyoHdk4Br1gBuDi18px5ucxXBuEwr6I6sl8LitgV4poyPCqODhuUFbkqD7ke7KEoCn1dccj7WvXqwJou4iXprRCBLwRO5QahlJeZOBbRDYN/LSQ4AuyvbpLGswSWNwkgWcABsbGk1sWwmlaSojVIlNMhvscd3zrBGj5HZ4AuF+kFZC2ko8ZLflDmC1OLNoTbNlBYQ1kxGcbmagvAE2PZZvjZzR3yEF8cZHnXac+EUW/Ft5CfkIv8jeH2CCl7Jw2LUqHMWaRyxglkCs6aBprBkzEkmDFQBdLEkMvVGr+cPT3e3iKIeIdWOXwA1EfnPCz1p/myMHATZiW2VCGENnIsv41vqZh9U0FmNRku9mo5fY8vYLvT4EMOSXaOjIiOt15/ouVgtYH0xXkJ1VCS7p+ELe3vco6skntp2758xblFtnd7tl68cSI6ABJ1aDW1rv913TJ49+wtiEw8h4w9TbZNwufjhvHwdqqw6HViVtV6XQkkJe+pUZmhCiMCHHU4pLatLiuK4z+6nTO422ggXG5EA4R+hXkTc5/hz+oPWnoZCiOxSqy1JeOE1HTOK+1xQNcF12vyod5OJnTb+fWq3zBNiy6XWdx+X3NgDEEix7xjC5FaQDjU9757BCDvTGmwrE2/pbVusd6g06/TeK18Y3s7PKRJlY9X0e/TncTLlFlmoH5zbRzABD48gwggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQI29i592IKdT0CAggABIIEyEGxJ8H0RI4yg9a0m3lzikeMjSKaSxPgFHuyw797xLckvtDXiYu8dWlSeKcGxDj3yD/FPOLJ4azEh+/kDyzCIT5MlKTVGAeMsa09miN9dWGoCS8p8ypwT7jphIMv/xtmCv/5ehT8YbXPTfy7y3YksDjEf51ZhnQGHk0eJr5yQGrkSTrLV4tLDhEqifc0r9idIiSpyZzbcuPUGOtsKizPj717Y9cTA7/u/ZXO8OB7UQ5Mz2YJO6lttnHqrbe4J/BfNwbV0Ko3s6j5nYgaymZZQ32CvxoF/phpdL3SRx9CW0TrEXkLAR8DDetVbJklxaXxy8T7xx+3IrMmYX2yVW2cniws+FBwf/7QCc3ehF9UKoKaDdz4LckMwaocE9Aa0FPTNaIUe9RpPvi3S/Tcvaj14Ig4HSnsbsm9c9xxducXZn1oVfOIcR9NLPY7IH/Dhb0BaGV2+P6wQ5zhixKE6kD1iBPK3nSt3bKPTV25JVKrrzw5yyOY92Tp/ugxlYhNZvSOm1SKrVaCf/0TsldbpYmBqzQFGhyezpd0SqTi97SwaHaKVnItTGs/USd+FNYcFCX0mk/QUIGSAf0u0+CZJDXQV5/YlFiUvwpzu2wANZZo7n4NGsG6l55kEt8ueGpx16aTBifjiIp/UB6rVANu1DwDnafbdcV96FlMpAUsPNpCiFroE4cTGanj1rDQPor9J5MJmp1fmuUeKKLJ8FPsmvLVJxXU12NkiZDJNUoP4BdDe0My7Crt4DmVJpOmSgBTx5bK18SQdn0oC381ZQiVr83qhjVuQMyzKesfNYpGKh6UZKff7AQ2yQjDOIjLZhh6xpqtc0iykYGoKdVuNcX/jVNML20fZivFdtmQcDSkdk08xJCHRHDLNjhUMoQLcP7V1rZ3imC1lipiXQg9WX7h7PV9CcZBRTmVO4YiuKLG0KrvRQjwMsao6iHM5rft0viojOICZYvdkb5EfnDR5OHo7W2HvVB0VPvG8MTsUjJ54FGywVixVeXKQNhvM+3gK+HzM0L3RiztbvFhpTbXbccGMSK6Ypelk0WTnqNgzGUI6Oznr88UT8lcYGf+azJrEq/ACbjxcaaSLYagKo3XTnO0aa5LKveloF/CrUpkApc7K7umjvPYniYllr6FAlGNxGvexxZqk5fILB2QFLziuIC1/gRzdNO0lAYCGTbCMp19DZ7F2cdY9GeVBXMAaqh+1KVI4gVEpa2AMNgUJzR6/27qWUpNoeXw3UXJntikJTV0GQrmlT6NfoNgWiiUN+2S+l5DNbl/V1tY0qPLWczeuml7f+ag/PNNzaNBQ9JckFk1eyOnS7Hzu6U7VyR1+U3OCxxCsr5L+A/ECk1hlrFNynyl9MeWr7RGOjJZngK4lg71RoB14r7z2VFvI0Wh7JI0zaKNPExuCcjQUxjZPuh1rE8p4dOuMWEZyr4rrECCYwAL8k+qY3jzBqLEcHMvfLnAuvFS85zjUTlljVCQnkl0DwToRe6Krlbyt/hesP6vsQxhyHQCeUXKCeCYbEMfFmwJDwYluVhPLxij0LlTupF1XQaTz9AchVWMgQePcbMjDys3fyax7br/oGxOJbZwun8HITatosz6JI+bAqozzgmDNmL9LWca1xQe7mjVBOmW2jElMCMGCSqGSIb3DQEJFTEWBBTsg9SsvGQY+qPxYA9pRP1u1JRSmjAxMCEwCQYFKw4DAhoFAAQU4ySZEjLK4TJugHYiVYl1Yir52DYECBj7kEP7gykGAgIIAA==
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_KEY_PASSWORD: bougie
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --win --mac --linux
